sudo: required
language: c
services:
  - docker

before_install:
  - docker build -t clannad .

script:
  - docker run clannad make test
  - docker run clannad make self
allow_failures:
  - docker run clannad make self
